databaseChangeLog:
  - preConditions:
      - dbms:
          type: postgresql
      - runningAs:
          username: ${AQTS_SCHEMA_OWNER_USERNAME}

  - changeSet:
      author: eorosz
      id: "create.index.${AQTS_SCHEMA_NAME}.datum_converted_values_json_data_id"
      changes:
        - sql: create index if not exists datum_converted_values_json_data_id on ${AQTS_SCHEMA_NAME}.datum_converted_values (partition_number, json_data_id);
        - rollback: drop index if exists ${AQTS_SCHEMA_NAME}.datum_converted_values_json_data_id;
