version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          dependency_name: "postgres"
          version_requirement: "10.7-alpine"
